/* GENERATED by scripts/images.mjs — do not edit by hand.
   For each imported WebP: its single raster fallback, and the WebP
   both encodings so the browser can decode a rendition that fits
   the box rather than the master. 63 images.
   Regenerate with: npm run images */

import { asset } from './asset';

import _0_algoverse_arena from '../assets/algoverse_arena.webp';
import _0_algoverse_arena_f from '../assets/algoverse_arena.jpg';
import _0_algoverse_arena_w0 from '../assets/algoverse_arena-400.webp';
import _0_algoverse_arena_w1 from '../assets/algoverse_arena-800.webp';
import _0_algoverse_arena_w2 from '../assets/algoverse_arena-1200.webp';
import _0_algoverse_arena_w3 from '../assets/algoverse_arena-1600.webp';
import _1_algoverse_complexity from '../assets/algoverse_complexity.webp';
import _1_algoverse_complexity_f from '../assets/algoverse_complexity.jpg';
import _1_algoverse_complexity_w0 from '../assets/algoverse_complexity-400.webp';
import _1_algoverse_complexity_w1 from '../assets/algoverse_complexity-800.webp';
import _1_algoverse_complexity_w2 from '../assets/algoverse_complexity-1200.webp';
import _1_algoverse_complexity_w3 from '../assets/algoverse_complexity-1600.webp';
import _2_algoverse_cover from '../assets/algoverse_cover.webp';
import _2_algoverse_cover_f from '../assets/algoverse_cover.jpg';
import _2_algoverse_cover_w0 from '../assets/algoverse_cover-400.webp';
import _2_algoverse_cover_w1 from '../assets/algoverse_cover-800.webp';
import _2_algoverse_cover_w2 from '../assets/algoverse_cover-1200.webp';
import _2_algoverse_cover_w3 from '../assets/algoverse_cover-1600.webp';
import _3_algoverse_dashboard from '../assets/algoverse_dashboard.webp';
import _3_algoverse_dashboard_f from '../assets/algoverse_dashboard.jpg';
import _3_algoverse_dashboard_w0 from '../assets/algoverse_dashboard-400.webp';
import _3_algoverse_dashboard_w1 from '../assets/algoverse_dashboard-800.webp';
import _3_algoverse_dashboard_w2 from '../assets/algoverse_dashboard-1200.webp';
import _3_algoverse_dashboard_w3 from '../assets/algoverse_dashboard-1600.webp';
import _4_algoverse_deck from '../assets/algoverse_deck.webp';
import _4_algoverse_deck_f from '../assets/algoverse_deck.jpg';
import _4_algoverse_deck_w0 from '../assets/algoverse_deck-400.webp';
import _4_algoverse_deck_w1 from '../assets/algoverse_deck-800.webp';
import _4_algoverse_deck_w2 from '../assets/algoverse_deck-1200.webp';
import _4_algoverse_deck_w3 from '../assets/algoverse_deck-1600.webp';
import _5_algoverse_hero from '../assets/algoverse_hero.webp';
import _5_algoverse_hero_f from '../assets/algoverse_hero.jpg';
import _5_algoverse_hero_w0 from '../assets/algoverse_hero-400.webp';
import _5_algoverse_hero_w1 from '../assets/algoverse_hero-800.webp';
import _5_algoverse_hero_w2 from '../assets/algoverse_hero-1200.webp';
import _5_algoverse_hero_w3 from '../assets/algoverse_hero-1600.webp';
import _6_algoverse_sorting from '../assets/algoverse_sorting.webp';
import _6_algoverse_sorting_f from '../assets/algoverse_sorting.jpg';
import _6_algoverse_sorting_w0 from '../assets/algoverse_sorting-400.webp';
import _6_algoverse_sorting_w1 from '../assets/algoverse_sorting-800.webp';
import _6_algoverse_sorting_w2 from '../assets/algoverse_sorting-1200.webp';
import _6_algoverse_sorting_w3 from '../assets/algoverse_sorting-1600.webp';
import _7_algoverse_treeinit from '../assets/algoverse_treeinit.webp';
import _7_algoverse_treeinit_f from '../assets/algoverse_treeinit.jpg';
import _7_algoverse_treeinit_w0 from '../assets/algoverse_treeinit-400.webp';
import _7_algoverse_treeinit_w1 from '../assets/algoverse_treeinit-800.webp';
import _7_algoverse_treeinit_w2 from '../assets/algoverse_treeinit-1200.webp';
import _8_algoverse_trees from '../assets/algoverse_trees.webp';
import _8_algoverse_trees_f from '../assets/algoverse_trees.jpg';
import _8_algoverse_trees_w0 from '../assets/algoverse_trees-400.webp';
import _8_algoverse_trees_w1 from '../assets/algoverse_trees-800.webp';
import _8_algoverse_trees_w2 from '../assets/algoverse_trees-1200.webp';
import _8_algoverse_trees_w3 from '../assets/algoverse_trees-1600.webp';
import _9_atlas_cover from '../assets/atlas_cover.webp';
import _9_atlas_cover_f from '../assets/atlas_cover.jpg';
import _9_atlas_cover_w0 from '../assets/atlas_cover-400.webp';
import _9_atlas_cover_w1 from '../assets/atlas_cover-800.webp';
import _10_atlas_graph from '../assets/atlas_graph.webp';
import _10_atlas_graph_f from '../assets/atlas_graph.jpg';
import _10_atlas_graph_w0 from '../assets/atlas_graph-400.webp';
import _10_atlas_graph_w1 from '../assets/atlas_graph-800.webp';
import _11_atlas_landing from '../assets/atlas_landing.webp';
import _11_atlas_landing_f from '../assets/atlas_landing.jpg';
import _11_atlas_landing_w0 from '../assets/atlas_landing-400.webp';
import _11_atlas_landing_w1 from '../assets/atlas_landing-800.webp';
import _11_atlas_landing_w2 from '../assets/atlas_landing-1200.webp';
import _11_atlas_landing_w3 from '../assets/atlas_landing-1600.webp';
import _12_atlas_papers from '../assets/atlas_papers.webp';
import _12_atlas_papers_f from '../assets/atlas_papers.jpg';
import _12_atlas_papers_w0 from '../assets/atlas_papers-400.webp';
import _12_atlas_papers_w1 from '../assets/atlas_papers-800.webp';
import _12_atlas_papers_w2 from '../assets/atlas_papers-1200.webp';
import _12_atlas_papers_w3 from '../assets/atlas_papers-1600.webp';
import _13_atlas_repositories from '../assets/atlas_repositories.webp';
import _13_atlas_repositories_f from '../assets/atlas_repositories.jpg';
import _13_atlas_repositories_w0 from '../assets/atlas_repositories-400.webp';
import _13_atlas_repositories_w1 from '../assets/atlas_repositories-800.webp';
import _13_atlas_repositories_w2 from '../assets/atlas_repositories-1200.webp';
import _13_atlas_repositories_w3 from '../assets/atlas_repositories-1600.webp';
import _14_comp_devjams from '../assets/comp_devjams.webp';
import _14_comp_devjams_f from '../assets/comp_devjams.jpg';
import _14_comp_devjams_w0 from '../assets/comp_devjams-400.webp';
import _15_comp_ey from '../assets/comp_ey.webp';
import _15_comp_ey_f from '../assets/comp_ey.jpg';
import _15_comp_ey_w0 from '../assets/comp_ey-400.webp';
import _16_comp_nec from '../assets/comp_nec.webp';
import _16_comp_nec_f from '../assets/comp_nec.jpg';
import _16_comp_nec_w0 from '../assets/comp_nec-400.webp';
import _17_comp_sih from '../assets/comp_sih.webp';
import _17_comp_sih_f from '../assets/comp_sih.jpg';
import _17_comp_sih_w0 from '../assets/comp_sih-400.webp';
import _18_dineguru_cover from '../assets/dineguru_cover.webp';
import _18_dineguru_cover_f from '../assets/dineguru_cover.jpg';
import _18_dineguru_cover_w0 from '../assets/dineguru_cover-400.webp';
import _18_dineguru_cover_w1 from '../assets/dineguru_cover-800.webp';
import _19_dineguru_integration from '../assets/dineguru_integration.webp';
import _19_dineguru_integration_f from '../assets/dineguru_integration.jpg';
import _19_dineguru_integration_w0 from '../assets/dineguru_integration-400.webp';
import _19_dineguru_integration_w1 from '../assets/dineguru_integration-800.webp';
import _19_dineguru_integration_w2 from '../assets/dineguru_integration-1200.webp';
import _19_dineguru_integration_w3 from '../assets/dineguru_integration-1600.webp';
import _20_dineguru_inventory from '../assets/dineguru_inventory.webp';
import _20_dineguru_inventory_f from '../assets/dineguru_inventory.jpg';
import _20_dineguru_inventory_w0 from '../assets/dineguru_inventory-400.webp';
import _20_dineguru_inventory_w1 from '../assets/dineguru_inventory-800.webp';
import _20_dineguru_inventory_w2 from '../assets/dineguru_inventory-1200.webp';
import _20_dineguru_inventory_w3 from '../assets/dineguru_inventory-1600.webp';
import _21_dineguru_kitchen from '../assets/dineguru_kitchen.webp';
import _21_dineguru_kitchen_f from '../assets/dineguru_kitchen.jpg';
import _21_dineguru_kitchen_w0 from '../assets/dineguru_kitchen-400.webp';
import _21_dineguru_kitchen_w1 from '../assets/dineguru_kitchen-800.webp';
import _22_dineguru_splash from '../assets/dineguru_splash.webp';
import _22_dineguru_splash_f from '../assets/dineguru_splash.jpg';
import _22_dineguru_splash_w0 from '../assets/dineguru_splash-400.webp';
import _22_dineguru_splash_w1 from '../assets/dineguru_splash-800.webp';
import _23_g_dineguru from '../assets/g_dineguru.webp';
import _23_g_dineguru_f from '../assets/g_dineguru.jpg';
import _23_g_dineguru_w0 from '../assets/g_dineguru-400.webp';
import _23_g_dineguru_w1 from '../assets/g_dineguru-800.webp';
import _23_g_dineguru_w2 from '../assets/g_dineguru-1200.webp';
import _24_g_netra from '../assets/g_netra.webp';
import _24_g_netra_f from '../assets/g_netra.jpg';
import _24_g_netra_w0 from '../assets/g_netra-400.webp';
import _24_g_netra_w1 from '../assets/g_netra-800.webp';
import _24_g_netra_w2 from '../assets/g_netra-1200.webp';
import _25_g_rockfall from '../assets/g_rockfall.webp';
import _25_g_rockfall_f from '../assets/g_rockfall.jpg';
import _25_g_rockfall_w0 from '../assets/g_rockfall-400.webp';
import _25_g_rockfall_w1 from '../assets/g_rockfall-800.webp';
import _25_g_rockfall_w2 from '../assets/g_rockfall-1200.webp';
import _26_hero_no_bg from '../assets/hero-no-bg.webp';
import _26_hero_no_bg_f from '../assets/hero-no-bg-fallback.png';
import _26_hero_no_bg_w0 from '../assets/hero-no-bg-400.webp';
import _26_hero_no_bg_w1 from '../assets/hero-no-bg-800.webp';
import _27_home_bench from '../assets/home_bench.webp';
import _27_home_bench_f from '../assets/home_bench.jpg';
import _27_home_bench_w0 from '../assets/home_bench-400.webp';
import _27_home_bench_w1 from '../assets/home_bench-800.webp';
import _27_home_bench_w2 from '../assets/home_bench-1200.webp';
import _28_home_cover from '../assets/home_cover.webp';
import _28_home_cover_f from '../assets/home_cover.jpg';
import _28_home_cover_w0 from '../assets/home_cover-400.webp';
import _29_home_leds from '../assets/home_leds.webp';
import _29_home_leds_f from '../assets/home_leds.jpg';
import _29_home_leds_w0 from '../assets/home_leds-400.webp';
import _29_home_leds_w1 from '../assets/home_leds-800.webp';
import _29_home_leds_w2 from '../assets/home_leds-1200.webp';
import _30_home_rig from '../assets/home_rig.webp';
import _30_home_rig_f from '../assets/home_rig.jpg';
import _30_home_rig_w0 from '../assets/home_rig-400.webp';
import _30_home_rig_w1 from '../assets/home_rig-800.webp';
import _30_home_rig_w2 from '../assets/home_rig-1200.webp';
import _31_home_shortlist from '../assets/home_shortlist.webp';
import _31_home_shortlist_f from '../assets/home_shortlist.jpg';
import _31_home_shortlist_w0 from '../assets/home_shortlist-400.webp';
import _31_home_shortlist_w1 from '../assets/home_shortlist-800.webp';
import _32_netra_build from '../assets/netra_build.webp';
import _32_netra_build_f from '../assets/netra_build.jpg';
import _32_netra_build_w0 from '../assets/netra_build-400.webp';
import _32_netra_build_w1 from '../assets/netra_build-800.webp';
import _33_netra_cover from '../assets/netra_cover.webp';
import _33_netra_cover_f from '../assets/netra_cover.jpg';
import _33_netra_cover_w0 from '../assets/netra_cover-400.webp';
import _33_netra_cover_w1 from '../assets/netra_cover-800.webp';
import _34_netra_unit from '../assets/netra_unit.webp';
import _34_netra_unit_f from '../assets/netra_unit.jpg';
import _34_netra_unit_w0 from '../assets/netra_unit-400.webp';
import _34_netra_unit_w1 from '../assets/netra_unit-800.webp';
import _35_recommender_cover from '../assets/recommender_cover.webp';
import _35_recommender_cover_f from '../assets/recommender_cover.jpg';
import _35_recommender_cover_w0 from '../assets/recommender_cover-400.webp';
import _35_recommender_cover_w1 from '../assets/recommender_cover-800.webp';
import _35_recommender_cover_w2 from '../assets/recommender_cover-1200.webp';
import _35_recommender_cover_w3 from '../assets/recommender_cover-1600.webp';
import _36_recommender_history from '../assets/recommender_history.webp';
import _36_recommender_history_f from '../assets/recommender_history.jpg';
import _36_recommender_history_w0 from '../assets/recommender_history-400.webp';
import _36_recommender_history_w1 from '../assets/recommender_history-800.webp';
import _36_recommender_history_w2 from '../assets/recommender_history-1200.webp';
import _36_recommender_history_w3 from '../assets/recommender_history-1600.webp';
import _37_recommender_landing from '../assets/recommender_landing.webp';
import _37_recommender_landing_f from '../assets/recommender_landing.jpg';
import _37_recommender_landing_w0 from '../assets/recommender_landing-400.webp';
import _37_recommender_landing_w1 from '../assets/recommender_landing-800.webp';
import _37_recommender_landing_w2 from '../assets/recommender_landing-1200.webp';
import _37_recommender_landing_w3 from '../assets/recommender_landing-1600.webp';
import _38_recommender_movies from '../assets/recommender_movies.webp';
import _38_recommender_movies_f from '../assets/recommender_movies.jpg';
import _38_recommender_movies_w0 from '../assets/recommender_movies-400.webp';
import _38_recommender_movies_w1 from '../assets/recommender_movies-800.webp';
import _38_recommender_movies_w2 from '../assets/recommender_movies-1200.webp';
import _38_recommender_movies_w3 from '../assets/recommender_movies-1600.webp';
import _39_recommender_music from '../assets/recommender_music.webp';
import _39_recommender_music_f from '../assets/recommender_music.jpg';
import _39_recommender_music_w0 from '../assets/recommender_music-400.webp';
import _39_recommender_music_w1 from '../assets/recommender_music-800.webp';
import _39_recommender_music_w2 from '../assets/recommender_music-1200.webp';
import _39_recommender_music_w3 from '../assets/recommender_music-1600.webp';
import _40_recommender_songs from '../assets/recommender_songs.webp';
import _40_recommender_songs_f from '../assets/recommender_songs.jpg';
import _40_recommender_songs_w0 from '../assets/recommender_songs-400.webp';
import _40_recommender_songs_w1 from '../assets/recommender_songs-800.webp';
import _40_recommender_songs_w2 from '../assets/recommender_songs-1200.webp';
import _40_recommender_songs_w3 from '../assets/recommender_songs-1600.webp';
import _41_recommender_title from '../assets/recommender_title.webp';
import _41_recommender_title_f from '../assets/recommender_title.jpg';
import _41_recommender_title_w0 from '../assets/recommender_title-400.webp';
import _41_recommender_title_w1 from '../assets/recommender_title-800.webp';
import _41_recommender_title_w2 from '../assets/recommender_title-1200.webp';
import _41_recommender_title_w3 from '../assets/recommender_title-1600.webp';
import _42_rockfall_alert from '../assets/rockfall_alert.webp';
import _42_rockfall_alert_f from '../assets/rockfall_alert.jpg';
import _42_rockfall_alert_w0 from '../assets/rockfall_alert-400.webp';
import _42_rockfall_alert_w1 from '../assets/rockfall_alert-800.webp';
import _42_rockfall_alert_w2 from '../assets/rockfall_alert-1200.webp';
import _42_rockfall_alert_w3 from '../assets/rockfall_alert-1600.webp';
import _43_rockfall_brand from '../assets/rockfall_brand.webp';
import _43_rockfall_brand_f from '../assets/rockfall_brand.jpg';
import _43_rockfall_brand_w0 from '../assets/rockfall_brand-400.webp';
import _43_rockfall_brand_w1 from '../assets/rockfall_brand-800.webp';
import _43_rockfall_brand_w2 from '../assets/rockfall_brand-1200.webp';
import _44_rockfall_cover from '../assets/rockfall_cover.webp';
import _44_rockfall_cover_f from '../assets/rockfall_cover.jpg';
import _44_rockfall_cover_w0 from '../assets/rockfall_cover-400.webp';
import _44_rockfall_cover_w1 from '../assets/rockfall_cover-800.webp';
import _44_rockfall_cover_w2 from '../assets/rockfall_cover-1200.webp';
import _44_rockfall_cover_w3 from '../assets/rockfall_cover-1600.webp';
import _45_rockfall_dashboard from '../assets/rockfall_dashboard.webp';
import _45_rockfall_dashboard_f from '../assets/rockfall_dashboard.jpg';
import _45_rockfall_dashboard_w0 from '../assets/rockfall_dashboard-400.webp';
import _45_rockfall_dashboard_w1 from '../assets/rockfall_dashboard-800.webp';
import _45_rockfall_dashboard_w2 from '../assets/rockfall_dashboard-1200.webp';
import _45_rockfall_dashboard_w3 from '../assets/rockfall_dashboard-1600.webp';
import _46_rockfall_detail from '../assets/rockfall_detail.webp';
import _46_rockfall_detail_f from '../assets/rockfall_detail.jpg';
import _46_rockfall_detail_w0 from '../assets/rockfall_detail-400.webp';
import _46_rockfall_detail_w1 from '../assets/rockfall_detail-800.webp';
import _46_rockfall_detail_w2 from '../assets/rockfall_detail-1200.webp';
import _46_rockfall_detail_w3 from '../assets/rockfall_detail-1600.webp';
import _47_rockfall_events from '../assets/rockfall_events.webp';
import _47_rockfall_events_f from '../assets/rockfall_events.jpg';
import _47_rockfall_events_w0 from '../assets/rockfall_events-400.webp';
import _47_rockfall_events_w1 from '../assets/rockfall_events-800.webp';
import _47_rockfall_events_w2 from '../assets/rockfall_events-1200.webp';
import _47_rockfall_events_w3 from '../assets/rockfall_events-1600.webp';
import _48_rockfall_readings from '../assets/rockfall_readings.webp';
import _48_rockfall_readings_f from '../assets/rockfall_readings.jpg';
import _48_rockfall_readings_w0 from '../assets/rockfall_readings-400.webp';
import _48_rockfall_readings_w1 from '../assets/rockfall_readings-800.webp';
import _48_rockfall_readings_w2 from '../assets/rockfall_readings-1200.webp';
import _48_rockfall_readings_w3 from '../assets/rockfall_readings-1600.webp';
import _49_rockfall_sensors from '../assets/rockfall_sensors.webp';
import _49_rockfall_sensors_f from '../assets/rockfall_sensors.jpg';
import _49_rockfall_sensors_w0 from '../assets/rockfall_sensors-400.webp';
import _49_rockfall_sensors_w1 from '../assets/rockfall_sensors-800.webp';
import _49_rockfall_sensors_w2 from '../assets/rockfall_sensors-1200.webp';
import _49_rockfall_sensors_w3 from '../assets/rockfall_sensors-1600.webp';
import _50_saturdays_cover from '../assets/saturdays_cover.webp';
import _50_saturdays_cover_f from '../assets/saturdays_cover.jpg';
import _50_saturdays_cover_w0 from '../assets/saturdays_cover-400.webp';
import _50_saturdays_cover_w1 from '../assets/saturdays_cover-800.webp';
import _51_saturdays_landing from '../assets/saturdays_landing.webp';
import _51_saturdays_landing_f from '../assets/saturdays_landing.jpg';
import _51_saturdays_landing_w0 from '../assets/saturdays_landing-400.webp';
import _51_saturdays_landing_w1 from '../assets/saturdays_landing-800.webp';
import _52_saturdays_signin from '../assets/saturdays_signin.webp';
import _52_saturdays_signin_f from '../assets/saturdays_signin.jpg';
import _52_saturdays_signin_w0 from '../assets/saturdays_signin-400.webp';
import _52_saturdays_signin_w1 from '../assets/saturdays_signin-800.webp';
import _53_saturdays_tracking from '../assets/saturdays_tracking.webp';
import _53_saturdays_tracking_f from '../assets/saturdays_tracking.jpg';
import _53_saturdays_tracking_w0 from '../assets/saturdays_tracking-400.webp';
import _53_saturdays_tracking_w1 from '../assets/saturdays_tracking-800.webp';
import _54_stock_traffic from '../assets/stock_traffic.webp';
import _54_stock_traffic_f from '../assets/stock_traffic.jpg';
import _54_stock_traffic_w0 from '../assets/stock_traffic-400.webp';
import _54_stock_traffic_w1 from '../assets/stock_traffic-800.webp';
import _54_stock_traffic_w2 from '../assets/stock_traffic-1200.webp';
import _55_studio_cover from '../assets/studio_cover.webp';
import _55_studio_cover_f from '../assets/studio_cover.jpg';
import _55_studio_cover_w0 from '../assets/studio_cover-400.webp';
import _55_studio_cover_w1 from '../assets/studio_cover-800.webp';
import _55_studio_cover_w2 from '../assets/studio_cover-1200.webp';
import _55_studio_cover_w3 from '../assets/studio_cover-1600.webp';
import _56_studio_lab from '../assets/studio_lab.webp';
import _56_studio_lab_f from '../assets/studio_lab.jpg';
import _56_studio_lab_w0 from '../assets/studio_lab-400.webp';
import _56_studio_lab_w1 from '../assets/studio_lab-800.webp';
import _57_studio_result from '../assets/studio_result.webp';
import _57_studio_result_f from '../assets/studio_result.jpg';
import _57_studio_result_w0 from '../assets/studio_result-400.webp';
import _57_studio_result_w1 from '../assets/studio_result-800.webp';
import _57_studio_result_w2 from '../assets/studio_result-1200.webp';
import _57_studio_result_w3 from '../assets/studio_result-1600.webp';
import _58_studio_welcome from '../assets/studio_welcome.webp';
import _58_studio_welcome_f from '../assets/studio_welcome.jpg';
import _58_studio_welcome_w0 from '../assets/studio_welcome-400.webp';
import _58_studio_welcome_w1 from '../assets/studio_welcome-800.webp';
import _59_traffic_bench from '../assets/traffic_bench.webp';
import _59_traffic_bench_f from '../assets/traffic_bench.jpg';
import _59_traffic_bench_w0 from '../assets/traffic_bench-400.webp';
import _59_traffic_bench_w1 from '../assets/traffic_bench-800.webp';
import _60_traffic_board from '../assets/traffic_board.webp';
import _60_traffic_board_f from '../assets/traffic_board.jpg';
import _60_traffic_board_w0 from '../assets/traffic_board-400.webp';
import _60_traffic_board_w1 from '../assets/traffic_board-800.webp';
import _61_traffic_cover from '../assets/traffic_cover.webp';
import _61_traffic_cover_f from '../assets/traffic_cover.jpg';
import _61_traffic_cover_w0 from '../assets/traffic_cover-400.webp';
import _62_traffic_rtl from '../assets/traffic_rtl.webp';
import _62_traffic_rtl_f from '../assets/traffic_rtl.jpg';
import _62_traffic_rtl_w0 from '../assets/traffic_rtl-400.webp';
import _62_traffic_rtl_w1 from '../assets/traffic_rtl-800.webp';
import _62_traffic_rtl_w2 from '../assets/traffic_rtl-1200.webp';
import _62_traffic_rtl_w3 from '../assets/traffic_rtl-1600.webp';

export interface ImageSet {
  /** Raster URL for browsers without WebP. */
  fallback: string;
  /** srcset for the WebP ladder. */
  webp: string;
  /** The master's intrinsic width, in pixels. */
  width: number;
  /** The master's intrinsic height, in pixels. */
  height: number;
}

export const IMAGES: Readonly<Record<string, ImageSet>> = {
  [asset(_0_algoverse_arena)]: {
    fallback: asset(_0_algoverse_arena_f),
    webp: `${asset(_0_algoverse_arena_w0)} 400w, ${asset(_0_algoverse_arena_w1)} 800w, ${asset(_0_algoverse_arena_w2)} 1200w, ${asset(_0_algoverse_arena_w3)} 1600w, ${asset(_0_algoverse_arena)} 1918w`,
    width: 1918,
    height: 1199,
  },
  [asset(_1_algoverse_complexity)]: {
    fallback: asset(_1_algoverse_complexity_f),
    webp: `${asset(_1_algoverse_complexity_w0)} 400w, ${asset(_1_algoverse_complexity_w1)} 800w, ${asset(_1_algoverse_complexity_w2)} 1200w, ${asset(_1_algoverse_complexity_w3)} 1600w, ${asset(_1_algoverse_complexity)} 1918w`,
    width: 1918,
    height: 1199,
  },
  [asset(_2_algoverse_cover)]: {
    fallback: asset(_2_algoverse_cover_f),
    webp: `${asset(_2_algoverse_cover_w0)} 400w, ${asset(_2_algoverse_cover_w1)} 800w, ${asset(_2_algoverse_cover_w2)} 1200w, ${asset(_2_algoverse_cover_w3)} 1600w, ${asset(_2_algoverse_cover)} 2009w`,
    width: 2009,
    height: 1408,
  },
  [asset(_3_algoverse_dashboard)]: {
    fallback: asset(_3_algoverse_dashboard_f),
    webp: `${asset(_3_algoverse_dashboard_w0)} 400w, ${asset(_3_algoverse_dashboard_w1)} 800w, ${asset(_3_algoverse_dashboard_w2)} 1200w, ${asset(_3_algoverse_dashboard_w3)} 1600w, ${asset(_3_algoverse_dashboard)} 1919w`,
    width: 1919,
    height: 1199,
  },
  [asset(_4_algoverse_deck)]: {
    fallback: asset(_4_algoverse_deck_f),
    webp: `${asset(_4_algoverse_deck_w0)} 400w, ${asset(_4_algoverse_deck_w1)} 800w, ${asset(_4_algoverse_deck_w2)} 1200w, ${asset(_4_algoverse_deck_w3)} 1600w, ${asset(_4_algoverse_deck)} 1918w`,
    width: 1918,
    height: 1199,
  },
  [asset(_5_algoverse_hero)]: {
    fallback: asset(_5_algoverse_hero_f),
    webp: `${asset(_5_algoverse_hero_w0)} 400w, ${asset(_5_algoverse_hero_w1)} 800w, ${asset(_5_algoverse_hero_w2)} 1200w, ${asset(_5_algoverse_hero_w3)} 1600w, ${asset(_5_algoverse_hero)} 2253w`,
    width: 2253,
    height: 1408,
  },
  [asset(_6_algoverse_sorting)]: {
    fallback: asset(_6_algoverse_sorting_f),
    webp: `${asset(_6_algoverse_sorting_w0)} 400w, ${asset(_6_algoverse_sorting_w1)} 800w, ${asset(_6_algoverse_sorting_w2)} 1200w, ${asset(_6_algoverse_sorting_w3)} 1600w, ${asset(_6_algoverse_sorting)} 1919w`,
    width: 1919,
    height: 1199,
  },
  [asset(_7_algoverse_treeinit)]: {
    fallback: asset(_7_algoverse_treeinit_f),
    webp: `${asset(_7_algoverse_treeinit_w0)} 400w, ${asset(_7_algoverse_treeinit_w1)} 800w, ${asset(_7_algoverse_treeinit_w2)} 1200w, ${asset(_7_algoverse_treeinit)} 1398w`,
    width: 1398,
    height: 874,
  },
  [asset(_8_algoverse_trees)]: {
    fallback: asset(_8_algoverse_trees_f),
    webp: `${asset(_8_algoverse_trees_w0)} 400w, ${asset(_8_algoverse_trees_w1)} 800w, ${asset(_8_algoverse_trees_w2)} 1200w, ${asset(_8_algoverse_trees_w3)} 1600w, ${asset(_8_algoverse_trees)} 1914w`,
    width: 1914,
    height: 1196,
  },
  [asset(_9_atlas_cover)]: {
    fallback: asset(_9_atlas_cover_f),
    webp: `${asset(_9_atlas_cover_w0)} 400w, ${asset(_9_atlas_cover_w1)} 800w, ${asset(_9_atlas_cover)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_10_atlas_graph)]: {
    fallback: asset(_10_atlas_graph_f),
    webp: `${asset(_10_atlas_graph_w0)} 400w, ${asset(_10_atlas_graph_w1)} 800w, ${asset(_10_atlas_graph)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_11_atlas_landing)]: {
    fallback: asset(_11_atlas_landing_f),
    webp: `${asset(_11_atlas_landing_w0)} 400w, ${asset(_11_atlas_landing_w1)} 800w, ${asset(_11_atlas_landing_w2)} 1200w, ${asset(_11_atlas_landing_w3)} 1600w, ${asset(_11_atlas_landing)} 2048w`,
    width: 2048,
    height: 1136,
  },
  [asset(_12_atlas_papers)]: {
    fallback: asset(_12_atlas_papers_f),
    webp: `${asset(_12_atlas_papers_w0)} 400w, ${asset(_12_atlas_papers_w1)} 800w, ${asset(_12_atlas_papers_w2)} 1200w, ${asset(_12_atlas_papers_w3)} 1600w, ${asset(_12_atlas_papers)} 2048w`,
    width: 2048,
    height: 1094,
  },
  [asset(_13_atlas_repositories)]: {
    fallback: asset(_13_atlas_repositories_f),
    webp: `${asset(_13_atlas_repositories_w0)} 400w, ${asset(_13_atlas_repositories_w1)} 800w, ${asset(_13_atlas_repositories_w2)} 1200w, ${asset(_13_atlas_repositories_w3)} 1600w, ${asset(_13_atlas_repositories)} 2048w`,
    width: 2048,
    height: 1074,
  },
  [asset(_14_comp_devjams)]: {
    fallback: asset(_14_comp_devjams_f),
    webp: `${asset(_14_comp_devjams_w0)} 400w, ${asset(_14_comp_devjams)} 800w`,
    width: 800,
    height: 1240,
  },
  [asset(_15_comp_ey)]: {
    fallback: asset(_15_comp_ey_f),
    webp: `${asset(_15_comp_ey_w0)} 400w, ${asset(_15_comp_ey)} 800w`,
    width: 800,
    height: 1240,
  },
  [asset(_16_comp_nec)]: {
    fallback: asset(_16_comp_nec_f),
    webp: `${asset(_16_comp_nec_w0)} 400w, ${asset(_16_comp_nec)} 800w`,
    width: 800,
    height: 1240,
  },
  [asset(_17_comp_sih)]: {
    fallback: asset(_17_comp_sih_f),
    webp: `${asset(_17_comp_sih_w0)} 400w, ${asset(_17_comp_sih)} 800w`,
    width: 800,
    height: 1240,
  },
  [asset(_18_dineguru_cover)]: {
    fallback: asset(_18_dineguru_cover_f),
    webp: `${asset(_18_dineguru_cover_w0)} 400w, ${asset(_18_dineguru_cover_w1)} 800w, ${asset(_18_dineguru_cover)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_19_dineguru_integration)]: {
    fallback: asset(_19_dineguru_integration_f),
    webp: `${asset(_19_dineguru_integration_w0)} 400w, ${asset(_19_dineguru_integration_w1)} 800w, ${asset(_19_dineguru_integration_w2)} 1200w, ${asset(_19_dineguru_integration_w3)} 1600w, ${asset(_19_dineguru_integration)} 2048w`,
    width: 2048,
    height: 1152,
  },
  [asset(_20_dineguru_inventory)]: {
    fallback: asset(_20_dineguru_inventory_f),
    webp: `${asset(_20_dineguru_inventory_w0)} 400w, ${asset(_20_dineguru_inventory_w1)} 800w, ${asset(_20_dineguru_inventory_w2)} 1200w, ${asset(_20_dineguru_inventory_w3)} 1600w, ${asset(_20_dineguru_inventory)} 2048w`,
    width: 2048,
    height: 1152,
  },
  [asset(_21_dineguru_kitchen)]: {
    fallback: asset(_21_dineguru_kitchen_f),
    webp: `${asset(_21_dineguru_kitchen_w0)} 400w, ${asset(_21_dineguru_kitchen_w1)} 800w, ${asset(_21_dineguru_kitchen)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_22_dineguru_splash)]: {
    fallback: asset(_22_dineguru_splash_f),
    webp: `${asset(_22_dineguru_splash_w0)} 400w, ${asset(_22_dineguru_splash_w1)} 800w, ${asset(_22_dineguru_splash)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_23_g_dineguru)]: {
    fallback: asset(_23_g_dineguru_f),
    webp: `${asset(_23_g_dineguru_w0)} 400w, ${asset(_23_g_dineguru_w1)} 800w, ${asset(_23_g_dineguru_w2)} 1200w, ${asset(_23_g_dineguru)} 1600w`,
    width: 1600,
    height: 1000,
  },
  [asset(_24_g_netra)]: {
    fallback: asset(_24_g_netra_f),
    webp: `${asset(_24_g_netra_w0)} 400w, ${asset(_24_g_netra_w1)} 800w, ${asset(_24_g_netra_w2)} 1200w, ${asset(_24_g_netra)} 1600w`,
    width: 1600,
    height: 1000,
  },
  [asset(_25_g_rockfall)]: {
    fallback: asset(_25_g_rockfall_f),
    webp: `${asset(_25_g_rockfall_w0)} 400w, ${asset(_25_g_rockfall_w1)} 800w, ${asset(_25_g_rockfall_w2)} 1200w, ${asset(_25_g_rockfall)} 1280w`,
    width: 1280,
    height: 800,
  },
  [asset(_26_hero_no_bg)]: {
    fallback: asset(_26_hero_no_bg_f),
    webp: `${asset(_26_hero_no_bg_w0)} 400w, ${asset(_26_hero_no_bg_w1)} 800w, ${asset(_26_hero_no_bg)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_27_home_bench)]: {
    fallback: asset(_27_home_bench_f),
    webp: `${asset(_27_home_bench_w0)} 400w, ${asset(_27_home_bench_w1)} 800w, ${asset(_27_home_bench_w2)} 1200w, ${asset(_27_home_bench)} 1536w`,
    width: 1536,
    height: 960,
  },
  [asset(_28_home_cover)]: {
    fallback: asset(_28_home_cover_f),
    webp: `${asset(_28_home_cover_w0)} 400w, ${asset(_28_home_cover)} 600w`,
    width: 600,
    height: 800,
  },
  [asset(_29_home_leds)]: {
    fallback: asset(_29_home_leds_f),
    webp: `${asset(_29_home_leds_w0)} 400w, ${asset(_29_home_leds_w1)} 800w, ${asset(_29_home_leds_w2)} 1200w, ${asset(_29_home_leds)} 1280w`,
    width: 1280,
    height: 800,
  },
  [asset(_30_home_rig)]: {
    fallback: asset(_30_home_rig_f),
    webp: `${asset(_30_home_rig_w0)} 400w, ${asset(_30_home_rig_w1)} 800w, ${asset(_30_home_rig_w2)} 1200w, ${asset(_30_home_rig)} 1280w`,
    width: 1280,
    height: 800,
  },
  [asset(_31_home_shortlist)]: {
    fallback: asset(_31_home_shortlist_f),
    webp: `${asset(_31_home_shortlist_w0)} 400w, ${asset(_31_home_shortlist_w1)} 800w, ${asset(_31_home_shortlist)} 1118w`,
    width: 1118,
    height: 699,
  },
  [asset(_32_netra_build)]: {
    fallback: asset(_32_netra_build_f),
    webp: `${asset(_32_netra_build_w0)} 400w, ${asset(_32_netra_build_w1)} 800w, ${asset(_32_netra_build)} 974w`,
    width: 974,
    height: 609,
  },
  [asset(_33_netra_cover)]: {
    fallback: asset(_33_netra_cover_f),
    webp: `${asset(_33_netra_cover_w0)} 400w, ${asset(_33_netra_cover_w1)} 800w, ${asset(_33_netra_cover)} 836w`,
    width: 836,
    height: 467,
  },
  [asset(_34_netra_unit)]: {
    fallback: asset(_34_netra_unit_f),
    webp: `${asset(_34_netra_unit_w0)} 400w, ${asset(_34_netra_unit_w1)} 800w, ${asset(_34_netra_unit)} 836w`,
    width: 836,
    height: 523,
  },
  [asset(_35_recommender_cover)]: {
    fallback: asset(_35_recommender_cover_f),
    webp: `${asset(_35_recommender_cover_w0)} 400w, ${asset(_35_recommender_cover_w1)} 800w, ${asset(_35_recommender_cover_w2)} 1200w, ${asset(_35_recommender_cover_w3)} 1600w, ${asset(_35_recommender_cover)} 1881w`,
    width: 1881,
    height: 866,
  },
  [asset(_36_recommender_history)]: {
    fallback: asset(_36_recommender_history_f),
    webp: `${asset(_36_recommender_history_w0)} 400w, ${asset(_36_recommender_history_w1)} 800w, ${asset(_36_recommender_history_w2)} 1200w, ${asset(_36_recommender_history_w3)} 1600w, ${asset(_36_recommender_history)} 1880w`,
    width: 1880,
    height: 1175,
  },
  [asset(_37_recommender_landing)]: {
    fallback: asset(_37_recommender_landing_f),
    webp: `${asset(_37_recommender_landing_w0)} 400w, ${asset(_37_recommender_landing_w1)} 800w, ${asset(_37_recommender_landing_w2)} 1200w, ${asset(_37_recommender_landing_w3)} 1600w, ${asset(_37_recommender_landing)} 1875w`,
    width: 1875,
    height: 1172,
  },
  [asset(_38_recommender_movies)]: {
    fallback: asset(_38_recommender_movies_f),
    webp: `${asset(_38_recommender_movies_w0)} 400w, ${asset(_38_recommender_movies_w1)} 800w, ${asset(_38_recommender_movies_w2)} 1200w, ${asset(_38_recommender_movies_w3)} 1600w, ${asset(_38_recommender_movies)} 1881w`,
    width: 1881,
    height: 1176,
  },
  [asset(_39_recommender_music)]: {
    fallback: asset(_39_recommender_music_f),
    webp: `${asset(_39_recommender_music_w0)} 400w, ${asset(_39_recommender_music_w1)} 800w, ${asset(_39_recommender_music_w2)} 1200w, ${asset(_39_recommender_music_w3)} 1600w, ${asset(_39_recommender_music)} 1883w`,
    width: 1883,
    height: 1177,
  },
  [asset(_40_recommender_songs)]: {
    fallback: asset(_40_recommender_songs_f),
    webp: `${asset(_40_recommender_songs_w0)} 400w, ${asset(_40_recommender_songs_w1)} 800w, ${asset(_40_recommender_songs_w2)} 1200w, ${asset(_40_recommender_songs_w3)} 1600w, ${asset(_40_recommender_songs)} 1887w`,
    width: 1887,
    height: 1179,
  },
  [asset(_41_recommender_title)]: {
    fallback: asset(_41_recommender_title_f),
    webp: `${asset(_41_recommender_title_w0)} 400w, ${asset(_41_recommender_title_w1)} 800w, ${asset(_41_recommender_title_w2)} 1200w, ${asset(_41_recommender_title_w3)} 1600w, ${asset(_41_recommender_title)} 1908w`,
    width: 1908,
    height: 1193,
  },
  [asset(_42_rockfall_alert)]: {
    fallback: asset(_42_rockfall_alert_f),
    webp: `${asset(_42_rockfall_alert_w0)} 400w, ${asset(_42_rockfall_alert_w1)} 800w, ${asset(_42_rockfall_alert_w2)} 1200w, ${asset(_42_rockfall_alert_w3)} 1600w, ${asset(_42_rockfall_alert)} 1919w`,
    width: 1919,
    height: 1199,
  },
  [asset(_43_rockfall_brand)]: {
    fallback: asset(_43_rockfall_brand_f),
    webp: `${asset(_43_rockfall_brand_w0)} 400w, ${asset(_43_rockfall_brand_w1)} 800w, ${asset(_43_rockfall_brand_w2)} 1200w, ${asset(_43_rockfall_brand)} 1448w`,
    width: 1448,
    height: 905,
  },
  [asset(_44_rockfall_cover)]: {
    fallback: asset(_44_rockfall_cover_f),
    webp: `${asset(_44_rockfall_cover_w0)} 400w, ${asset(_44_rockfall_cover_w1)} 800w, ${asset(_44_rockfall_cover_w2)} 1200w, ${asset(_44_rockfall_cover_w3)} 1600w, ${asset(_44_rockfall_cover)} 1919w`,
    width: 1919,
    height: 887,
  },
  [asset(_45_rockfall_dashboard)]: {
    fallback: asset(_45_rockfall_dashboard_f),
    webp: `${asset(_45_rockfall_dashboard_w0)} 400w, ${asset(_45_rockfall_dashboard_w1)} 800w, ${asset(_45_rockfall_dashboard_w2)} 1200w, ${asset(_45_rockfall_dashboard_w3)} 1600w, ${asset(_45_rockfall_dashboard)} 1919w`,
    width: 1919,
    height: 1199,
  },
  [asset(_46_rockfall_detail)]: {
    fallback: asset(_46_rockfall_detail_f),
    webp: `${asset(_46_rockfall_detail_w0)} 400w, ${asset(_46_rockfall_detail_w1)} 800w, ${asset(_46_rockfall_detail_w2)} 1200w, ${asset(_46_rockfall_detail_w3)} 1600w, ${asset(_46_rockfall_detail)} 1911w`,
    width: 1911,
    height: 1194,
  },
  [asset(_47_rockfall_events)]: {
    fallback: asset(_47_rockfall_events_f),
    webp: `${asset(_47_rockfall_events_w0)} 400w, ${asset(_47_rockfall_events_w1)} 800w, ${asset(_47_rockfall_events_w2)} 1200w, ${asset(_47_rockfall_events_w3)} 1600w, ${asset(_47_rockfall_events)} 1912w`,
    width: 1912,
    height: 1195,
  },
  [asset(_48_rockfall_readings)]: {
    fallback: asset(_48_rockfall_readings_f),
    webp: `${asset(_48_rockfall_readings_w0)} 400w, ${asset(_48_rockfall_readings_w1)} 800w, ${asset(_48_rockfall_readings_w2)} 1200w, ${asset(_48_rockfall_readings_w3)} 1600w, ${asset(_48_rockfall_readings)} 1916w`,
    width: 1916,
    height: 1198,
  },
  [asset(_49_rockfall_sensors)]: {
    fallback: asset(_49_rockfall_sensors_f),
    webp: `${asset(_49_rockfall_sensors_w0)} 400w, ${asset(_49_rockfall_sensors_w1)} 800w, ${asset(_49_rockfall_sensors_w2)} 1200w, ${asset(_49_rockfall_sensors_w3)} 1600w, ${asset(_49_rockfall_sensors)} 1917w`,
    width: 1917,
    height: 1198,
  },
  [asset(_50_saturdays_cover)]: {
    fallback: asset(_50_saturdays_cover_f),
    webp: `${asset(_50_saturdays_cover_w0)} 400w, ${asset(_50_saturdays_cover_w1)} 800w, ${asset(_50_saturdays_cover)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_51_saturdays_landing)]: {
    fallback: asset(_51_saturdays_landing_f),
    webp: `${asset(_51_saturdays_landing_w0)} 400w, ${asset(_51_saturdays_landing_w1)} 800w, ${asset(_51_saturdays_landing)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_52_saturdays_signin)]: {
    fallback: asset(_52_saturdays_signin_f),
    webp: `${asset(_52_saturdays_signin_w0)} 400w, ${asset(_52_saturdays_signin_w1)} 800w, ${asset(_52_saturdays_signin)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_53_saturdays_tracking)]: {
    fallback: asset(_53_saturdays_tracking_f),
    webp: `${asset(_53_saturdays_tracking_w0)} 400w, ${asset(_53_saturdays_tracking_w1)} 800w, ${asset(_53_saturdays_tracking)} 1024w`,
    width: 1024,
    height: 1024,
  },
  [asset(_54_stock_traffic)]: {
    fallback: asset(_54_stock_traffic_f),
    webp: `${asset(_54_stock_traffic_w0)} 400w, ${asset(_54_stock_traffic_w1)} 800w, ${asset(_54_stock_traffic_w2)} 1200w, ${asset(_54_stock_traffic)} 1600w`,
    width: 1600,
    height: 1400,
  },
  [asset(_55_studio_cover)]: {
    fallback: asset(_55_studio_cover_f),
    webp: `${asset(_55_studio_cover_w0)} 400w, ${asset(_55_studio_cover_w1)} 800w, ${asset(_55_studio_cover_w2)} 1200w, ${asset(_55_studio_cover_w3)} 1600w, ${asset(_55_studio_cover)} 2048w`,
    width: 2048,
    height: 1152,
  },
  [asset(_56_studio_lab)]: {
    fallback: asset(_56_studio_lab_f),
    webp: `${asset(_56_studio_lab_w0)} 400w, ${asset(_56_studio_lab_w1)} 800w, ${asset(_56_studio_lab)} 866w`,
    width: 866,
    height: 487,
  },
  [asset(_57_studio_result)]: {
    fallback: asset(_57_studio_result_f),
    webp: `${asset(_57_studio_result_w0)} 400w, ${asset(_57_studio_result_w1)} 800w, ${asset(_57_studio_result_w2)} 1200w, ${asset(_57_studio_result_w3)} 1600w, ${asset(_57_studio_result)} 2048w`,
    width: 2048,
    height: 1152,
  },
  [asset(_58_studio_welcome)]: {
    fallback: asset(_58_studio_welcome_f),
    webp: `${asset(_58_studio_welcome_w0)} 400w, ${asset(_58_studio_welcome_w1)} 800w, ${asset(_58_studio_welcome)} 860w`,
    width: 860,
    height: 484,
  },
  [asset(_59_traffic_bench)]: {
    fallback: asset(_59_traffic_bench_f),
    webp: `${asset(_59_traffic_bench_w0)} 400w, ${asset(_59_traffic_bench_w1)} 800w, ${asset(_59_traffic_bench)} 859w`,
    width: 859,
    height: 537,
  },
  [asset(_60_traffic_board)]: {
    fallback: asset(_60_traffic_board_f),
    webp: `${asset(_60_traffic_board_w0)} 400w, ${asset(_60_traffic_board_w1)} 800w, ${asset(_60_traffic_board)} 867w`,
    width: 867,
    height: 542,
  },
  [asset(_61_traffic_cover)]: {
    fallback: asset(_61_traffic_cover_f),
    webp: `${asset(_61_traffic_cover_w0)} 400w, ${asset(_61_traffic_cover)} 715w`,
    width: 715,
    height: 542,
  },
  [asset(_62_traffic_rtl)]: {
    fallback: asset(_62_traffic_rtl_f),
    webp: `${asset(_62_traffic_rtl_w0)} 400w, ${asset(_62_traffic_rtl_w1)} 800w, ${asset(_62_traffic_rtl_w2)} 1200w, ${asset(_62_traffic_rtl_w3)} 1600w, ${asset(_62_traffic_rtl)} 2349w`,
    width: 2349,
    height: 1468,
  },
  '/certificates/bserc-iisc-drone-workshop.webp': {
    fallback: '/certificates/bserc-iisc-drone-workshop.jpg',
    webp: '/certificates/bserc-iisc-drone-workshop-400.webp 400w, /certificates/bserc-iisc-drone-workshop-800.webp 800w, /certificates/bserc-iisc-drone-workshop-1200.webp 1200w, /certificates/bserc-iisc-drone-workshop.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/ey-manthana-round-two.webp': {
    fallback: '/certificates/ey-manthana-round-two.jpg',
    webp: '/certificates/ey-manthana-round-two-400.webp 400w, /certificates/ey-manthana-round-two-800.webp 800w, /certificates/ey-manthana-round-two-1200.webp 1200w, /certificates/ey-manthana-round-two.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/governai-internship.webp': {
    fallback: '/certificates/governai-internship.jpg',
    webp: '/certificates/governai-internship-400.webp 400w, /certificates/governai-internship-800.webp 800w, /certificates/governai-internship-1200.webp 1200w, /certificates/governai-internship.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/iitg-encode-udgam.webp': {
    fallback: '/certificates/iitg-encode-udgam.jpg',
    webp: '/certificates/iitg-encode-udgam-400.webp 400w, /certificates/iitg-encode-udgam-800.webp 800w, /certificates/iitg-encode-udgam-1200.webp 1200w, /certificates/iitg-encode-udgam.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/iitropar-ai-major.webp': {
    fallback: '/certificates/iitropar-ai-major.jpg',
    webp: '/certificates/iitropar-ai-major-400.webp 400w, /certificates/iitropar-ai-major-800.webp 800w, /certificates/iitropar-ai-major-1200.webp 1200w, /certificates/iitropar-ai-major.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/layover-uiux-internship.webp': {
    fallback: '/certificates/layover-uiux-internship.jpg',
    webp: '/certificates/layover-uiux-internship-400.webp 400w, /certificates/layover-uiux-internship-800.webp 800w, /certificates/layover-uiux-internship-1200.webp 1200w, /certificates/layover-uiux-internship.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/layover-uiux-letter.webp': {
    fallback: '/certificates/layover-uiux-letter.jpg',
    webp: '/certificates/layover-uiux-letter-400.webp 400w, /certificates/layover-uiux-letter-800.webp 800w, /certificates/layover-uiux-letter-1200.webp 1200w, /certificates/layover-uiux-letter.webp 1500w',
    width: 1500,
    height: 2000,
  },
  '/certificates/linkedin-microsoft-career-essentials.webp': {
    fallback: '/certificates/linkedin-microsoft-career-essentials.jpg',
    webp: '/certificates/linkedin-microsoft-career-essentials-400.webp 400w, /certificates/linkedin-microsoft-career-essentials-800.webp 800w, /certificates/linkedin-microsoft-career-essentials-1200.webp 1200w, /certificates/linkedin-microsoft-career-essentials.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/linkedin-microsoft-genai.webp': {
    fallback: '/certificates/linkedin-microsoft-genai.jpg',
    webp: '/certificates/linkedin-microsoft-genai-400.webp 400w, /certificates/linkedin-microsoft-genai-800.webp 800w, /certificates/linkedin-microsoft-genai-1200.webp 1200w, /certificates/linkedin-microsoft-genai.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/linkedin-programming-foundations.webp': {
    fallback: '/certificates/linkedin-programming-foundations.jpg',
    webp: '/certificates/linkedin-programming-foundations-400.webp 400w, /certificates/linkedin-programming-foundations-800.webp 800w, /certificates/linkedin-programming-foundations-1200.webp 1200w, /certificates/linkedin-programming-foundations.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/nec-2024-ecell-iitb.webp': {
    fallback: '/certificates/nec-2024-ecell-iitb.jpg',
    webp: '/certificates/nec-2024-ecell-iitb-400.webp 400w, /certificates/nec-2024-ecell-iitb-800.webp 800w, /certificates/nec-2024-ecell-iitb-1200.webp 1200w, /certificates/nec-2024-ecell-iitb.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/sjmsom-prod-wars.webp': {
    fallback: '/certificates/sjmsom-prod-wars.jpg',
    webp: '/certificates/sjmsom-prod-wars-400.webp 400w, /certificates/sjmsom-prod-wars-800.webp 800w, /certificates/sjmsom-prod-wars-1200.webp 1200w, /certificates/sjmsom-prod-wars.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/certificates/vubs-appreciation.webp': {
    fallback: '/certificates/vubs-appreciation.jpg',
    webp: '/certificates/vubs-appreciation-400.webp 400w, /certificates/vubs-appreciation-800.webp 800w, /certificates/vubs-appreciation-1200.webp 1200w, /certificates/vubs-appreciation.webp 1414w',
    width: 1414,
    height: 1000,
  },
  '/insights/devjams.webp': {
    fallback: '/insights/devjams.jpg',
    webp: '/insights/devjams-400.webp 400w, /insights/devjams-800.webp 800w, /insights/devjams.webp 1158w',
    width: 1158,
    height: 795,
  },
  '/insights/electroutsav.webp': {
    fallback: '/insights/electroutsav.jpg',
    webp: '/insights/electroutsav-400.webp 400w, /insights/electroutsav-800.webp 800w, /insights/electroutsav-1200.webp 1200w, /insights/electroutsav.webp 1248w',
    width: 1248,
    height: 1128,
  },
  '/insights/first-internship.webp': {
    fallback: '/insights/first-internship.jpg',
    webp: '/insights/first-internship-400.webp 400w, /insights/first-internship.webp 800w',
    width: 800,
    height: 672,
  },
  '/insights/iit-ropar-complete.webp': {
    fallback: '/insights/iit-ropar-complete.jpg',
    webp: '/insights/iit-ropar-complete-400.webp 400w, /insights/iit-ropar-complete-800.webp 800w, /insights/iit-ropar-complete-1200.webp 1200w, /insights/iit-ropar-complete.webp 1280w',
    width: 1280,
    height: 1229,
  },
  '/insights/iit-ropar-convocation.webp': {
    fallback: '/insights/iit-ropar-convocation.jpg',
    webp: '/insights/iit-ropar-convocation-400.webp 400w, /insights/iit-ropar-convocation.webp 698w',
    width: 698,
    height: 1050,
  },
  '/insights/iit-ropar-major.webp': {
    fallback: '/insights/iit-ropar-major.jpg',
    webp: '/insights/iit-ropar-major-400.webp 400w, /insights/iit-ropar-major.webp 720w',
    width: 720,
    height: 435,
  },
  '/insights/nec-iit-bombay.webp': {
    fallback: '/insights/nec-iit-bombay.jpg',
    webp: '/insights/nec-iit-bombay-400.webp 400w, /insights/nec-iit-bombay.webp 646w',
    width: 646,
    height: 582,
  },
  '/insights/nec-visionary-ventures.webp': {
    fallback: '/insights/nec-visionary-ventures.jpg',
    webp: '/insights/nec-visionary-ventures-400.webp 400w, /insights/nec-visionary-ventures-800.webp 800w, /insights/nec-visionary-ventures.webp 1152w',
    width: 1152,
    height: 912,
  },
  '/insights/smart-india-hack.webp': {
    fallback: '/insights/smart-india-hack.jpg',
    webp: '/insights/smart-india-hack-400.webp 400w, /insights/smart-india-hack-800.webp 800w, /insights/smart-india-hack.webp 1165w',
    width: 1165,
    height: 941,
  },
  '/insights/startup-summit.webp': {
    fallback: '/insights/startup-summit.jpg',
    webp: '/insights/startup-summit-400.webp 400w, /insights/startup-summit-800.webp 800w, /insights/startup-summit-1200.webp 1200w, /insights/startup-summit.webp 1600w',
    width: 1600,
    height: 1200,
  },
  '/insights/submissions-closed.webp': {
    fallback: '/insights/submissions-closed.jpg',
    webp: '/insights/submissions-closed-400.webp 400w, /insights/submissions-closed-800.webp 800w, /insights/submissions-closed-1200.webp 1200w, /insights/submissions-closed.webp 1280w',
    width: 1280,
    height: 960,
  },
  '/insights/summit-floor.webp': {
    fallback: '/insights/summit-floor.jpg',
    webp: '/insights/summit-floor-400.webp 400w, /insights/summit-floor-800.webp 800w, /insights/summit-floor.webp 992w',
    width: 992,
    height: 740,
  },
};
